name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.BILAL_SECRET_NAME }}
        password: ${{ secrets.BILAL_SECRET_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: bilal62462/devopslab:latest

